package gotweet

const CREATE_TWITTER_DATABASE = `CREATE DATABASE twitter;`

const DROP_TWITTER_DATABASE = `DROP DATABASE IF EXISTS twitter CASCADE;`

const CREATE_USERS_SCHEMA = `CREATE SCHEMA IF NOT EXISTS users;`

const DROP_USERS_SCHEMA = `DROP SCHEMA IF EXISTS users CASCADE;`

const DROP_USER_BLOCKS_TYPES = `
DROP TYPE IF EXISTS
	withheld_scope,
	user_withheld,
	user_url_expansion,
	_user_url_expansion,
	user_hashtag,
	_user_hashtag,
	mention,
	_mention,
	user_cashtag,
	_user_cashtag,
	user_description,
	user_entities_url,
	user_entities,
	user_public_metrics
CASCADE;`

const DROP_USER_BLOCKS_TABLE = `
DROP TABLE IF EXISTS users.blocks CASCADE;
`

const CREATE_USER_BLOCKS_TABLE = `
CREATE TABLE IF NOT EXISTS users.blocks(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	twitter_id VARCHAR (128),
	name VARCHAR (128),
	username VARCHAR (128),
	created_at DATE,
	protected BOOLEAN,
    withheld user_withheld,
	location VARCHAR (128),
	url VARCHAR (128),
	description VARCHAR (256),
	verified BOOLEAN,
	entities user_entities,
	public_image_url VARCHAR (128),
	public_metrics user_public_metrics,
	pinned_tweet_id VARCHAR (128)
);`

const INSERT_INTO_USER_BLOCKS = `
INSERT INTO users.blocks(
	twitter_id,
	name,
	username,
	created_at,
	protected,
	withheld,
	location,
	url,
	description,
	verified,
	entities,
	public_image_url,
	public_metrics,
	pinned_tweet_id
)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14);
`

const CREATE_WITHHELD_SCOPE_TYPE = `
CREATE TYPE withheld_scope AS ENUM ('tweet', 'user');`

const GET_WITHHELD_SCOPE_TYPE_OID = `
SELECT oid FROM pg_type WHERE typname = 'withheld_scope';
`

const CREATE_USER_WITHHELD_TYPE = `
CREATE TYPE user_withheld AS(
	country_codes VARCHAR (128)[],
	scope withheld_scope
);`

const CREATE_USER_URL_EXPANSION_TYPE = `
CREATE TYPE user_url_expansion AS(
	start smallint,
	"end" smallint,
	url VARCHAR (128),
	expanded_url VARCHAR (128),
	display_url VARCHAR (128)
);`

const CREATE_USER_HASHTAG_TYPE = `
CREATE TYPE user_hashtag AS(
	 start smallint,
	 "end" smallint,
	 tag VARCHAR (128)
);`

const CREATE_MENTION_TYPE = `
CREATE TYPE mention AS(
	 start smallint,
	 "end" smallint,
	 username VARCHAR (128)
);`

const CREATE_USER_CASHTAG_TYPE = `
CREATE TYPE user_cashtag AS(
	 start smallint,
	 "end" smallint,
	 tag VARCHAR (128)
);`

// v2 api has incorrect documentation
const CREATE_USER_DESCRIPTION_TYPE = `
CREATE TYPE user_description AS(
	 urls user_url_expansion[],
	 hashtags user_hashtag[],
	 mentions mention[],
	 cashtags user_cashtag[]
);`

const CREATE_USER_ENTITIES_URL_TYPE = `
CREATE TYPE user_entities_url AS(
	urls user_url_expansion[]
)
`
const CREATE_USER_ENTITIES_TYPE = `
CREATE TYPE user_entities AS(
	url user_entities_url,
	description user_description
);`

const CREATE_USER_PUBLIC_METRICS_TYPE = `
CREATE TYPE user_public_metrics AS(
	followers_count bigint,
	following_count bigint,
	tweet_count bigint,
	listed_count bigint
);`
